# Generated by Django 2.1.3 on 2018-11-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
